spring.application.name=auth-service
server.port=8082

keycloak.url=${KEYCLOAK_URL:http://localhost:8090}
keycloak.realm=${KEYCLOAK_REALM:StreamHub}
keycloak.client-id=${KEYCLOAK_CLIENT_ID:streamhub-backend}
keycloak.client-secret=${KEYCLOAK_CLIENT_SECRET}
keycloak.admin-user=${KEYCLOAK_ADMIN:admin}
keycloak.admin-password=${KEYCLOAK_ADMIN_PASSWORD:admin_dev_2024}

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8090/realms/StreamHub

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

spring.mvc.problemdetails.enabled=true

management.endpoints.web.exposure.include=health,info

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.enabled=false