keycloak.url=http://keycloak:8080
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://keycloak:8090/realms/StreamHub/protocol/openid-connect/certs
spring.kafka.bootstrap-servers=redpanda:9092
