spring.application.name=movie-service
server.port=8083

spring.mongodb.uri=mongodb://${MONGO_INITDB_ROOT_USERNAME:streamflix}:${MONGO_INITDB_ROOT_PASSWORD:mongo_dev_2024}@localhost:27017/${MONGO_INITDB_DATABASE:movie_db}?authSource=admin

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=${REDIS_PASSWORD:redis_dev_2024}

minio.url=http://localhost:9000
minio.access-key=${MINIO_ROOT_USER:streamflix}
minio.secret-key=${MINIO_ROOT_PASSWORD:minio_dev_2024}
minio.bucket.movies=${MINIO_BUCKET_MOVIES:movies}
minio.bucket.thumbnails=${MINIO_BUCKET_THUMBNAILS:thumbnails}

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8090/realms/StreamHub/protocol/openid-connect/certs

spring.mvc.problemdetails.enabled=true
management.endpoints.web.exposure.include=health,info

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.enabled=false
