spring.mongodb.host=mongodb
spring.mongodb.port=27017
spring.mongodb.database=${MONGO_INITDB_DATABASE}
spring.mongodb.username=${MONGO_INITDB_ROOT_USERNAME}
spring.mongodb.password=${MONGO_INITDB_ROOT_PASSWORD}
spring.mongodb.authentication-database=admin
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB
spring.data.redis.host=redis
minio.url=http://minio:9000
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://keycloak:8090/realms/StreamHub/protocol/openid-connect/certs
